name: Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'maven'

      - name: Build and Test
        run: mvn clean package

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER@L}" >> "${GITHUB_ENV}"
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${OWNER_LC}/authenticationservice:${{ github.sha }} .
          docker tag ghcr.io/${OWNER_LC}/authenticationservice:${{ github.sha }} ghcr.io/${OWNER_LC}/authenticationservice:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${OWNER_LC}/authenticationservice:${{ github.sha }}
          docker push ghcr.io/${OWNER_LC}/authenticationservice:latest